// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy5ZX2f-wMgOuYMtq-4JiZMkImPLPn0Co',
    appId: '1:916180170981:android:c02130853673aac3d3fc0c',
    messagingSenderId: '916180170981',
    projectId: 'second-dacfd',
    databaseURL: 'https://second-dacfd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'second-dacfd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuQ8ckA6GbWt1Wui__5E9hUN6txZNsHPg',
    appId: '1:916180170981:ios:40dadf6dcbc0e47ed3fc0c',
    messagingSenderId: '916180170981',
    projectId: 'second-dacfd',
    databaseURL: 'https://second-dacfd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'second-dacfd.appspot.com',
    iosClientId: '916180170981-ffg6foju8bar635tpurorak15pmb32kr.apps.googleusercontent.com',
    iosBundleId: 'com.example.customChatCleanArchitectureWithLoginFirebase',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOh5OLDTu-jnA6QdisJlFUm65oZnBuX2Q',
    appId: '1:916180170981:web:0ae305ec44818825d3fc0c',
    messagingSenderId: '916180170981',
    projectId: 'second-dacfd',
    authDomain: 'second-dacfd.firebaseapp.com',
    databaseURL: 'https://second-dacfd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'second-dacfd.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuQ8ckA6GbWt1Wui__5E9hUN6txZNsHPg',
    appId: '1:916180170981:ios:40dadf6dcbc0e47ed3fc0c',
    messagingSenderId: '916180170981',
    projectId: 'second-dacfd',
    databaseURL: 'https://second-dacfd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'second-dacfd.appspot.com',
    iosClientId: '916180170981-ffg6foju8bar635tpurorak15pmb32kr.apps.googleusercontent.com',
    iosBundleId: 'com.example.customChatCleanArchitectureWithLoginFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOm1AxRssOk_b96LNq1QDlUQMrS65jfMw',
    appId: '1:916180170981:web:469d783ecaa6c0d4d3fc0c',
    messagingSenderId: '916180170981',
    projectId: 'second-dacfd',
    authDomain: 'second-dacfd.firebaseapp.com',
    databaseURL: 'https://second-dacfd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'second-dacfd.appspot.com',
  );

}