platform :ios, '12.0'  # Use iOS 11 or above, as App Center supports it

target 'Runner' do
  # Use static frameworks to avoid dynamic linking issues
  use_frameworks! :linkage => :static

  # Specify local path for App Center frameworks
  pod 'AppCenter', :path => '../AppCenterSDKs/AppCenter'
  pod 'AppCenterAnalytics', :path => '../AppCenterSDKs/AppCenterAnalytics'
  pod 'AppCenterCrashes', :path => '../AppCenterSDKs/AppCenterCrashes'
  # Uncomment the following line if you need the Distribute module
  # pod 'AppCenterDistribute', :path => '../AppCenterSDKs/AppCenterDistribute'

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end